services:
  framework-api:
    build: 
      context : .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATA_URL: http://datafetch-api:8000/
      AHP_URL: http://ahp-api:8080/
    networks:
      - shared
networks:
  shared:
    external: true
    name: anv-net
